### ISSUE TITLE
Check ob Devices im LAN/WLAN aktiv sind

### ISSUE THREAD

**Issue by Apollon77** [iobroker-community-adapters/ioBroker.fritzbox#12]
Um Anwesenheitschecks zu machen ist eine Idee, die auch schon im HM-Forum diskutiert wurde, zu prüfen ob bestimmte Geräte aktiv im LAN/WLAN sind.

Von daher wäre es super hier eine Möglichkeit zu haben so etwas abzufragen - vllt als Kommaliste mit Devicenamen in der Konfig und es werden dann diese Geräte geprüft und als Variablen angelegt oder so ...

**Comment by ruhr70** [comment]
Das nutze ich schon lange, direkt in ioBroker.
Das kannst Du mit dem Ping Adapter realisieren.

**Comment by Apollon77** [comment]
Ich hatte gelesen das die Ping-Idee nicht mit IPhones geht ... Da man Sie immer aufwecken müsste dafür ...

**Comment by ruhr70** [comment]
Ja, das ist richtig. 
Bei mir funktioniert das trotzdem sehr gut, da ich das mit einem Türkontakt kombiniert habe. Und die Info Tür zu mit dem Ping kombiniere. D.h. wenn die Tür geschlossen wurde und ich nach einer definierten Pause danach Ping empfange, dann st das iPhone anwesend (vereinfacht aufgeführt). Wenn die iPhones nach dem heimkommen ans Ladegerät gehangen werden oder mal kurz aktiv sind, kann man sie in Verbindung mit der  Information vom Türkontakt als Anwesend zählen.
Aber richtig. Mit einer "generellen WLAN-Anwesenheit" wäre es einfacher abzubilden.

**Comment by Apollon77** [comment]
Wenn du sowas einbauen könntest wäre das cool ... Zwischenzeitlich bastle ich mal mit der ping-Idee ... Da ich mein iphone aber nur nachts lade müsste man schauen ob das funktioniert ;-)
Ebenso (was interessanter ist) das Erkennen von "Abwesenheit" ist interesanter ...
Mit welcher "Pause" arbeitest Du?

**Comment by ruhr70** [comment]
Momentan ist es leider nicht aktiv (neue ioBroker Installation). hat aber echt gut funktioniert.
Es reichte schon, wenn man zwischendurch den Homebutten gedrückt hatte und das Telefon aktiv wurde.

Pause... wie war das...
insgesamt hatte ich etwas länger daran gesessen. 

Von der Vorgehensweise habe ich mir ein Chart gebaut, in dem die Zustände visualisiert wurden. Türkontakt. Anwesenheit meiner Frau, Anwesenheit von mir, Bewegungsmelder, tlw. Lichtschalter, usw. Um das auseinanderzuhalten, haben die einzelnen Werte bei true immer unterschiedliche Werte um die 1 erhalten und bei false Werte um die 0, alles mit unterschiedlichen Farben.

Zusätzlich habe ich mir vorher die Logik, wann passiert was, auf Papier aufgezeichnet.

Ich meine, ich hätte es am Ende so eingestellt, dass ein erkannter Ping , der nach zwei Minuten nach dem letzten Schliessen der Tür für ein Anwesend gesorgt hat. Hängt etwas davon ab, wie lange man sich außerhalb der geschlossen Tür noch im WLAN Bereich aufhält/aufhalten.

Umgesetzt hatte ich es mit Node-Red, würde heute aber Javascript nehmen und es um Owntracks und/oder Geofency Infos ergänzen.

**Comment by Apollon77** [comment]
Alsi ich hab nochmal getestet und ich nutze aktuell Geofency UND Fritzbox-WLAN-Device-Presence. In der Fritzbox ist das Gerät nämlich als im WLAN aktiv aufgeführt auch wenn man es neben sich liegen hat. Und PING geht nur wenn es aktiv ist (Sperrbildschirm und so)

**Comment by kxn25** [comment]
https://www.youtube.com/watch?v=oWe7hE8HOaU&t=7s
