### ISSUE TITLE
Datenpunkttypen korrigieren

### ISSUE THREAD

**Issue by ruhr70** [iobroker-community-adapters/ioBroker.fritzbox#18]
Beispiel:

Counter: rings missed

Ist vom Typ String und sollte Number sein

**Comment by Khaos66** [comment]
+1 
Wobei man string auf number manuell korrigieren kann.

Was ich bisher nicht hinbekommen habe sind die States connectNumbers und ringActualNumbers.
Hier bekomme ich im Log immer nur 
```
State value to set for "fritzbox.0.calls.connectNumbers" has to be stringified but received type "object"
State value to set for "fritzbox.0.calls.ringActualNumbers" has to be stringified but received type "object"
```

**Comment by Khaos66** [comment]
Wenn ich das richtig sehe könnte das mit PR #42 gefixt werden...
