### ISSUE TITLE
fritzbox.0.history.missedTableJSON  wird nicht gefüllt

### ISSUE THREAD

**Issue by ruhr70** [iobroker-community-adapters/ioBroker.fritzbox#19]
siehe Betreff

**Comment by MikeEcho0815** [comment]
Kann ich bestätigen, bei mir auch nicht.

**Comment by fischmir** [comment]
Hier ebenfalls. Damit macht dann auch das Widget für die VIS kaum Sinn, oder? Wird das gefixt werden? Ist ja nun schon seit 2 Jahren offen... :-(

**Comment by UweLoyal** [comment]
Nach 4 Jahren ist dieses issue immer noch offen!
Dürfte doch nicht schwer sein zu fixen?

**Comment by Apollon77** [comment]
>  Dürfte doch nicht schwer sein zu fixen?

Darf ich frech antworten: Dann machs doch ;-)

Bitte Debug log bereitstellen

**Comment by Apollon77** [comment]
Faktisch war es einfach nicht implementiert - bitte GitHub versuchen

**Comment by Apollon77** [comment]
fixed by next verwion
