### ISSUE TITLE
Adapter funktioniert nicht mehr

### ISSUE THREAD

**Issue by derchirurg** [iobroker-community-adapters/ioBroker.fritzbox#26]
Hallo,

ich habe den Adapter installiert, in der FritzBox den Port 1012 freigeschaltet und die IP im Adapter eingetragen. Im Log wird angezeigt, dass eine Verbindung zur FB hergestellt werden kann.
adapter connected to fritzbox

Allerdings bekomme ich keine Daten, weder in den Objects, noch (logischerweise) im vis Widget.

**Comment by Apollon77** [comment]
Noch relevant?
