### ISSUE TITLE
Aktualisierung Dokumentation

### ISSUE THREAD

**Issue by maloross** [iobroker-community-adapters/ioBroker.fritzbox#28]
Aktuell wird die komplette Dokumentation von ioBroker neu strukturiert und überarbeitet. 
1. Ist dies hier der aktuelle Stand der Dokumentation?
2. In der Konfiguration finden sich u.a. die Einstellungsmöglichkeiten "Bridge", "Polling" usw. die laut <a href="https://forum.iobroker.net/viewtopic.php?f=20&t=3344&hilit=fritzbox" title="Titel">
diesem Thread im ioBroker-Forum</a> da eigentlich nicht vorgesehen waren. Findet ggf. noch eine abschließende Überarbeitung statt?

**Comment by ruhr70** [comment]
Bridge, Pollong, usw. wird nicht benötigt und gehört da eigentlich auch nicht rein.
Müsste nachsehen, ob das in meiner Version drin war und Restlasten einer Vorlage war.
Der Adapter ist zweimal nicht von mir erweitert worden, start von TR-64. Da gab es danach einen eigenen TR-64 Adapter.
Im Prinzip einmal zurück auf die erste Version des Adapters.
Muss ich mir anschauen.
