### ISSUE TITLE
MissedDateReset ist INVALID

### ISSUE THREAD

**Issue by MikeEcho0815** [iobroker-community-adapters/ioBroker.fritzbox#32]
"MissedDateReset" gibt bei mir ein Invalid Date.

Könnte ich diesen Wert nutzen, um die "MissedCalls" zu löschen? Wenn ja, welches Format muss das Datum haben?

**Comment by Apollon77** [comment]
Zeigt das aktuellste Beta Admin 5.3.3. oder so auch noch Invalid date an?
