### ISSUE TITLE
blocked incoming calls are not reset

### ISSUE THREAD

**Issue by 150d** [iobroker-community-adapters/ioBroker.fritzbox#40]
Hi,

i have added a phone number to the "blocked" list in FritzBox. Now, when a call from this number arrives, it is indicated, but never cleared in ioBroker:

fritzbox.0.calls.counterActualCalls.allActiveCount remains at 1
fritzbox.0.calls.counterActualCalls.ringCount remains at 1

These states (possibly others as well) remain set indefinitly, until a new call comes in that is not blocked (regardless of whether the new call is picked up or not, it always clears the states.)

The log looks like this:

`
fritzbox.0 | 2021-05-06 16:56:11.385 | info | (4133) data from [IP]: 06.05.21 16:56:11;DISCONNECT;0;0;
fritzbox.0 | 2021-05-06 16:56:11.382 | info | (4133) data from [IP]: 06.05.21 16:56:11;RING;0;[blockedCaller];[myNumber];SIP13;
`

Regards

**Comment by Apollon77** [comment]
Question is how the adapter shpuld differentiate a "blocked caller" from one that simply "hung up"?

**Comment by Apollon77** [comment]
Ok, please try GitHub version and provide a debug log (change loglevel of instance to debug vis admin - instances (Expertmode enabled) - expand instance in instance list and change loglevel of such a blocked call

**Comment by 150d** [comment]
I'm afraid I can't do that easily - after encountering this issue last year I changed to another adapter ("tr-064") which was working better for me. Thus, I no longer have "fritzbox" installed. ;-)

Sorry about that. If noone else is experiencing this issue and it can't be reproduced feel free to close this defect.

**Comment by Apollon77** [comment]
ok, then we do that ...
