### ISSUE TITLE
connected without retyping the password and other issues

### ISSUE THREAD

**Issue by wendy2702** [iobroker-community-adapters/ioBroker.fritzbox#49]
I just updated the Adapter to 0.4.0.

Immediatly after the update was finished the adapter was able to connect to the FB with retyping the password:

`
2022-03-30 15:21:47.667  - info: fritzbox.0 (16784) starting. Version 0.4.0 in /opt/iobroker/node_modules/iobroker.fritzbox, node: v14.19.0, js-controller: 4.0.21`
`2022-03-30 15:21:47.689  - info: fritzbox.0 (16784) try to connect: 192.168.2.1`
`2022-03-30 15:21:47.696  - info: fritzbox.0 (16784) adapter connected to fritzbox: 192.168.2.1`

On Dark Mode it's hard to read the Adapter Config page:

![grafik](https://user-images.githubusercontent.com/33424168/160847945-814b28f9-885e-4843-8576-5d16b1c60def.png)

Is the field showing "dslf-config" the Username field and is the field below for the password?

Clicking the question mark icon at for the Adapter leads to an very old description which needs to be updated.

![grafik](https://user-images.githubusercontent.com/33424168/160848795-e7d16b63-362a-4eab-b643-fca67771f82c.png)

![grafik](https://user-images.githubusercontent.com/33424168/160849091-5be582d0-01d2-46a6-b0fa-4eb8e67c8811.png)

Changelog not updated as well:

![grafik](https://user-images.githubusercontent.com/33424168/160849217-9e3580e0-0d22-4e66-b29f-8f95cad2fb50.png)

**Comment by Apollon77** [comment]
Hi !

1.) The "connected" messages is logged when the network connection was done - the password is only used when certain functions are used where TR-064 is neede (e.g. Phonebook, TAM, Wlan control) SO might be "Missleading logging"

2.) Design: Yes needs to be upgraded for Admin 3+ ... maybe next time or someone else does it. I focussed on functionality, duplicate #25 

3.) Outdated readme should be fixed on some days with updated website
