### ISSUE TITLE
Update Host auf 5.0.12

### ISSUE THREAD

**Issue by Axklein** [iobroker-community-adapters/ioBroker.fritzbox#83]
Hallo , das ist mein erstes Issue. Ich hoffen die Beschreibung ist so Ok.

nach update des Hots auf 5.0.12 startet der Fritzbox-Adapter nicht mehr.
Fehlermeldungen:

<html>
<body>

host.IOBROKER-U59 | 2023-09-18 17:25:10.346 | error | instance system.adapter.fritzbox.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.IOBROKER-U59 | 2023-09-18 17:25:10.346 | error | Caught by controller[0]: }
host.IOBROKER-U59 | 2023-09-18 17:25:10.346 | error | Caught by controller[0]: ]
host.IOBROKER-U59 | 2023-09-18 17:25:10.346 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.fritzbox/main.js'
host.IOBROKER-U59 | 2023-09-18 17:25:10.346 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.fritzbox/lib/utils.js',
host.IOBROKER-U59 | 2023-09-18 17:25:10.346 | error | Caught by controller[0]: requireStack: [
host.IOBROKER-U59 | 2023-09-18 17:25:10.346 | error | Caught by controller[0]: code: 'MODULE_NOT_FOUND',
host.IOBROKER-U59 | 2023-09-18 17:25:10.346 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1100:19) {
host.IOBROKER-U59 | 2023-09-18 17:25:10.346 | error | Caught by controller[0]: at Function.Module._load (node:internal/modules/cjs/loader:911:12)
host.IOBROKER-U59 | 2023-09-18 17:25:10.346 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:1076:32)
host.IOBROKER-U59 | 2023-09-18 17:25:10.346 | error | Caught by controller[0]: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
host.IOBROKER-U59 | 2023-09-18 17:25:10.346 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1198:14)
host.IOBROKER-U59 | 2023-09-18 17:25:10.346 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.fritzbox/lib/utils.js:46:25)
host.IOBROKER-U59 | 2023-09-18 17:25:10.346 | error | Caught by controller[0]: at require (node:internal/modules/cjs/helpers:119:18)
host.IOBROKER-U59 | 2023-09-18 17:25:10.346 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1100:19)
host.IOBROKER-U59 | 2023-09-18 17:25:10.346 | error | Caught by controller[0]: at Function.Module._load (node:internal/modules/cjs/loader:873:27)
host.IOBROKER-U59 | 2023-09-18 17:25:10.346 | error | Caught by controller[0]: at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
host.IOBROKER-U59 | 2023-09-18 17:25:10.345 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.fritzbox/main.js
host.IOBROKER-U59 | 2023-09-18 17:25:10.345 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.fritzbox/lib/utils.js
host.IOBROKER-U59 | 2023-09-18 17:25:10.345 | error | Caught by controller[0]: Require stack:
host.IOBROKER-U59 | 2023-09-18 17:25:10.345 | error | Caught by controller[0]: Error: Cannot find module '/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js'
host.IOBROKER-U59 | 2023-09-18 17:25:10.345 | error | Caught by controller[0]: ^
host.IOBROKER-U59 | 2023-09-18 17:25:10.345 | error | Caught by controller[0]: throw err;
host.IOBROKER-U59 | 2023-09-18 17:25:10.345 | error | Caught by controller[0]: node:internal/modules/cjs/loader:1031

</body>
</html>

**Versions:** 
System:
Plattform linux
Betriebssystem  linux  ubuntu 22.04
Architektur x64
CPUs 4
Geschwindigkeit 2875 MHz
Modell Intel(R) Celeron(R) N5095 @ 2.00GHz
RAM 7.53 GB
Node.js v16.20.2 (Empfohlene Version v18.17.1)
NPM 8.19.4
Anzahl der Adapter 498
Fritzbox-Adapterversion: 0.2.1

**Comment by mcm1957** [comment]
Problem ist mit Version 0.5.0 behoben sein,
Die Version 0.5.0 ist im LATEST repo verfügbar und sollte ab morgen auch im stable Repository angeboten werden.

Sollte das Problem auch mit Version 0.5.0 noch auftreten, bitte das Issue neu öffnen bzw Bescheid geben.
